# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sh bin/docker/writeAzureRegistry.sh
  displayName: 'Set up NPM'

- script: |
    npm ci
  displayName: 'npm install'

- script: |
    npm run lint
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'npm lint'

- script: |
    npm run build
  displayName: 'npm build'

- script: |
    npm run test:ci
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'npm test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    mergeTestResults: true
    testRunTitle: 'Publish result'
